# Generated by Django 4.0.2 on 2022-03-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=70)),
                ('email', models.CharField(default='', max_length=70)),
                ('address', models.CharField(default='', max_length=70)),
                ('address2', models.CharField(default='', max_length=70)),
                ('city', models.CharField(default='', max_length=70)),
                ('state', models.CharField(default='', max_length=70)),
                ('zip', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.DeleteModel(
            name='check',
        ),
    ]
